/*
 * DisplaySV300Measurements.java
 * 
 * this class is used to display some messurments from ventilator, freq, expVolum,
 * inspVolum, peep, pip (Breath data), and airway flow, insp. press. and exsp. press.
 *
 * Created on 15. juli 2004, 13:29
 */

package icumatic.device.sv300.gui;

import java.util.*;
import icumatic.device.sv300.*;
import icumatic.toolkit.*;

/**
 *
 * @author  yichun
 */
public class DisplaySV300Measurements extends javax.swing.JDialog implements Observer {
    
    /** Creates new form DisplaySV300Measurements */
    public DisplaySV300Measurements(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DisplaySV300Measurements(java.awt.Frame parent, boolean modal, DataModel dataModel) {
        super(parent, modal);
        initComponents();
        this.dataModel = dataModel;
        this.dataModel.addObserver(this);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAirwayFlow = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldInspPress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldExspPress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPeak = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPeep = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldFreq = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldInspTidal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldExspTidal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldUpperPressLimit = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servo 300 Messurements");
        setName("DisplaySV300Mesasurements");
        setResizable(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(8, 8, 4, 8)));
        jPanel3.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jPanel1.setLayout(new java.awt.GridLayout(9, 3, 10, 10));

        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Measurements"));
        jPanel1.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel1.setText(" Airway Flow");
        jLabel1.setAlignmentX(0.2F);
        jLabel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        jPanel1.add(jLabel1);

        jTextFieldAirwayFlow.setEditable(false);
        jTextFieldAirwayFlow.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldAirwayFlow.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldAirwayFlow.setText("0.00");
        jTextFieldAirwayFlow.setName("airwayFlow");
        jPanel1.add(jTextFieldAirwayFlow);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel2.setText(" l/s");
        jLabel2.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel3.setText(" Insp. Airway Press.");
        jLabel3.setAlignmentX(0.2F);
        jLabel3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        jPanel1.add(jLabel3);

        jTextFieldInspPress.setEditable(false);
        jTextFieldInspPress.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldInspPress.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldInspPress.setText("0.00");
        jPanel1.add(jTextFieldInspPress);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel4.setText(" cm H20");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel5.setText(" Exsp. Airway Press.");
        jLabel5.setAlignmentX(0.2F);
        jPanel1.add(jLabel5);

        jTextFieldExspPress.setEditable(false);
        jTextFieldExspPress.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldExspPress.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldExspPress.setText("0.00");
        jPanel1.add(jTextFieldExspPress);

        jLabel6.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel6.setText(" cm H20");
        jPanel1.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel7.setText(" Insp. Peak Press.");
        jLabel7.setAlignmentX(0.2F);
        jPanel1.add(jLabel7);

        jTextFieldPeak.setEditable(false);
        jTextFieldPeak.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldPeak.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldPeak.setText("0.00");
        jPanel1.add(jTextFieldPeak);

        jLabel8.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel8.setText(" cm H20");
        jPanel1.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel9.setText(" End exp. Press.");
        jLabel9.setAlignmentX(0.2F);
        jPanel1.add(jLabel9);

        jTextFieldPeep.setEditable(false);
        jTextFieldPeep.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldPeep.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldPeep.setText("0.00");
        jPanel1.add(jTextFieldPeep);

        jLabel10.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel10.setText(" cm H20");
        jPanel1.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel11.setText(" Resp. Freq.");
        jLabel11.setAlignmentX(0.2F);
        jPanel1.add(jLabel11);

        jTextFieldFreq.setEditable(false);
        jTextFieldFreq.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldFreq.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldFreq.setText("0.00");
        jPanel1.add(jTextFieldFreq);

        jLabel12.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel12.setText(" b/min");
        jPanel1.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel13.setText(" Insp. Tidal Vol.");
        jLabel13.setAlignmentX(0.2F);
        jPanel1.add(jLabel13);

        jTextFieldInspTidal.setEditable(false);
        jTextFieldInspTidal.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldInspTidal.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldInspTidal.setText("0.00");
        jPanel1.add(jTextFieldInspTidal);

        jLabel14.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel14.setText(" ml");
        jPanel1.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel15.setText(" Exp. Tidal Vol.");
        jLabel15.setAlignmentX(0.2F);
        jPanel1.add(jLabel15);

        jTextFieldExspTidal.setEditable(false);
        jTextFieldExspTidal.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldExspTidal.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldExspTidal.setText("0.00");
        jPanel1.add(jTextFieldExspTidal);

        jLabel16.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel16.setText(" ml");
        jPanel1.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel17.setText("Upper pres. limit");
        jLabel17.setAlignmentX(0.2F);
        jPanel1.add(jLabel17);

        jTextFieldUpperPressLimit.setEditable(false);
        jTextFieldUpperPressLimit.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jTextFieldUpperPressLimit.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jTextFieldUpperPressLimit.setText("0.00");
        jPanel1.add(jTextFieldUpperPressLimit);

        jLabel18.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jLabel18.setText(" cm H20");
        jPanel1.add(jLabel18);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 8, 8, 8)));
        jButton1.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-418)/2, 400, 418);
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        new DisplaySV300Measurements(new javax.swing.JFrame(), true).show();
//    }
    
    public void update(Observable o, Object arg) {
        double airwayFlow = this.dataModel.getAirwayFlow();
        String str = DecimalFormatDemo.customFormat("#0.000", airwayFlow/1000);
        this.jTextFieldAirwayFlow.setText(str);

        double inspTidalVol = this.dataModel.getInspTidalVolume();
        this.jTextFieldInspTidal.setText(Double.toString(inspTidalVol));
        
        double expTidalVol = this.dataModel.getExpTidalVolume();
        this.jTextFieldExspTidal.setText(Double.toString(expTidalVol));
        
        double inspAirwayPress = this.dataModel.getInspireAirwayPressure();
        String str1 = DecimalFormatDemo.customFormat("#0.000", inspAirwayPress);
        this.jTextFieldInspPress.setText(str1);
        
        double exspAirwayPress = this.dataModel.getExpireAirwayPressure();
        String str2 = DecimalFormatDemo.customFormat("#0.000", exspAirwayPress);        
        this.jTextFieldExspPress.setText(str2);
        
        double peep = this.dataModel.getPeep();
        this.jTextFieldPeep.setText(Double.toString(peep));
        
        double peak = this.dataModel.getPip();
        this.jTextFieldPeak.setText(Double.toString(peak));
                
        int freq = this.dataModel.getFrequency();
        this.jTextFieldFreq.setText(Integer.toString(freq));
        
        double upperPressLimitSet = this.dataModel.getUpperPressLimitSet();
        this.jTextFieldUpperPressLimit.setText(Double.toString(upperPressLimitSet));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldAirwayFlow;
    private javax.swing.JTextField jTextFieldExspPress;
    private javax.swing.JTextField jTextFieldExspTidal;
    private javax.swing.JTextField jTextFieldFreq;
    private javax.swing.JTextField jTextFieldInspPress;
    private javax.swing.JTextField jTextFieldInspTidal;
    private javax.swing.JTextField jTextFieldPeak;
    private javax.swing.JTextField jTextFieldPeep;
    private javax.swing.JTextField jTextFieldUpperPressLimit;
    // End of variables declaration//GEN-END:variables
    private DataModel dataModel;
}
