/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DAConverter */

#ifndef _Included_DAConverter
#define _Included_DAConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DAConverter
 * Method:    AOWrite
 * Signature: (SSS)S
 */
JNIEXPORT jshort JNICALL Java_DAConverter_AOWrite
  (JNIEnv *, jobject, jshort, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
