/*
 * ExperimentIndicator.java
 *
 * Created on 8. september 2004, 16:04
 */

package servo300controller;

/**
 *
 * @author  yichun
 */
public class ExperimentIndicator extends javax.swing.JDialog {
    
    /** Creates new form ExperimentIndicator */
    public ExperimentIndicator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ExperimentIndicator() {
        super();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumBreath = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFlow = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPplat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Experiment Indicator");
        setFont(new java.awt.Font("Arial", 0, 12));
        setName("Experiment Indicator");
        setResizable(false);
        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 8, 8));

        jPanel1.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)), new javax.swing.border.EtchedBorder()));
        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 0, 18));
        jLabel1.setText("The ");
        jPanel2.add(jLabel1);

        jLabelNumBreath.setFont(new java.awt.Font("MS Sans Serif", 1, 18));
        jLabelNumBreath.setForeground(java.awt.SystemColor.textHighlight);
        jLabelNumBreath.setText("jLabel2");
        jPanel2.add(jLabelNumBreath);
        jLabelNumBreath.getAccessibleContext().setAccessibleName("numberOfBreath");

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 0, 18));
        jLabel3.setText("th. small breath,");
        jPanel2.add(jLabel3);

        jPanel1.add(jPanel2);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 0, 18));
        jLabel4.setText("by inflation flow rate");
        jPanel3.add(jLabel4);

        jLabelFlow.setFont(new java.awt.Font("MS Sans Serif", 1, 18));
        jLabelFlow.setForeground(java.awt.SystemColor.textHighlight);
        jLabelFlow.setText("jLabel5");
        jPanel3.add(jLabelFlow);
        jLabelFlow.getAccessibleContext().setAccessibleName("flowRate");

        jLabel6.setFont(new java.awt.Font("MS Sans Serif", 0, 18));
        jLabel6.setText("l/s,");
        jPanel3.add(jLabel6);

        jPanel1.add(jPanel3);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 0, 18));
        jLabel2.setText("in plateau pressure");
        jPanel4.add(jLabel2);

        jLabelPplat.setFont(new java.awt.Font("MS Sans Serif", 1, 18));
        jLabelPplat.setForeground(java.awt.SystemColor.textHighlight);
        jLabelPplat.setText("jLabel5");
        jPanel4.add(jLabelPplat);

        jLabel7.setFont(new java.awt.Font("MS Sans Serif", 0, 18));
        jLabel7.setText("cm H20.");
        jPanel4.add(jLabel7);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(512, 384, 340, 150);
    }//GEN-END:initComponents
    
    /**
     * method, setting ithNumberofSmallBreath
     */ 
    public void setNumberofBreath(int num){
        this.jLabelNumBreath.setText( Integer.toString(num));
    };
    
    /**
     * method, setting the inflation flow during small breath
     */
    public void setInflationFlow(double flow){
        this.jLabelFlow.setText( Double.toString(flow) );
    }

    /**
     * method, setting the Plateau pressure text 
     */
    public void setPplat(double Pplat){
        this.jLabelPplat.setText( Double.toString(Pplat) );
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        new ExperimentIndicator(new javax.swing.JFrame(), true).show();
//        
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFlow;
    private javax.swing.JLabel jLabelNumBreath;
    private javax.swing.JLabel jLabelPplat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    
}
